
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

language: go

before_install:
    sudo apt-get update &&
    sudo apt-get dist-upgrade &&
    sudo apt-get install curl wget gnupg2 make fakeroot-ng checkinstall &&
    sudo adduser i2pbrowser


install:
    make download easy all

script:
    make download easy all
