
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.12'
version_full = ''
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

